# Generated by Django 5.1.4 on 2024-12-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(auto_created=True, max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('about', models.TextField(verbose_name='')),
                ('Postion', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'SDE'), ('Project Leader', 'PL')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_data')),
            ],
        ),
    ]
