# Generated by Django 5.1.4 on 2024-12-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Postion',
            new_name='Position',
        ),
    ]
